### PR TITLE
Correction for ISO C++17 standard and README update

### PR DESCRIPTION
**Pull request by ksomml**
This did not compile for ROS2 Foxy/Humble.
With this correction it compiles properly now and can be used in these ROS2 versions.

### CODE REVIEW

**Comment by qleonardolp** [comment]
I'm sorry for the late reply. I'll be reviewing your contribution next weekend. It's good to see some interest on this package after all this years.

**Comment by ksomml** [comment]
Hey @qleonardolp,
previously, I intended to merge this with @ChangcongWang 's fork. It seems I made a mistake back then.

This was just a quick "hack" to get the package to build for ROS2, which requires higher C++ standards than ROS1. I recommend not merging this into the main branch. It might still work this way for ROS1.

I've been privately modifying @ChangcongWang 's ROS2 fork of your repository for my needs, but I recently noticed that the Xsens library files specify that modification or making these files public is not allowed. Therefore, I haven't published any more commits to my own fork. I've contacted Xsens last week about it to confirm whether modifying and publishing these older library files is permitted so I can be sure to be on the safe side when I publish it onto GitHub.

**Comment by qleonardolp** [comment]
> Hey @qleonardolp, previously, I intended to merge this with @ChangcongWang 's fork. It seems I made a mistake back then.
> 
> This was just a quick "hack" to get the package to build for ROS2, which requires higher C++ standards than ROS1. I recommend not merging this into the main branch. It might still work this way for ROS1.
> 
> I've been privately modifying @ChangcongWang 's ROS2 fork of your repository for my needs, but I recently noticed that the Xsens library files specify that modification or making these files public is not allowed. Therefore, I haven't published any more commits to my own fork. I've contacted Xsens last week about it to confirm whether modifying and publishing these older library files is permitted so I can be sure to be on the safe side when I publish it onto GitHub.

Understood. Let's keep in touch about the vendor libraries. I'm also looking for way to be on the safe side in this package. As far as I know, the related SDK is now [officially distributed here](https://base.movella.com/s/article/Installing-the-correct-Software-Suite-for-different-generation-products?language=en_US).

**Comment by ksomml** [comment]
> Understood. Let's keep in touch about the vendor libraries. I'm also looking for way to be on the safe side in this package. As far as I know, the related SDK is now [officially distributed here](https://base.movella.com/s/article/Installing-the-correct-Software-Suite-for-different-generation-products?language=en_US).

I compared the libraries included in the MT Software Suite for Linux to the ones in your repository last week. It appears they have made some updates to both the libraries and their copyright notice, which now seems to allow modifications. However, after reading the EULA that comes with the MT Software Suite, it states that modifications are not permitted. This was also a reason why I contacted them for clarification about this. My guess is that the copyright of the older Xsens libraries in your repository has likely expired.

I will update you once I receive more information from Xsens. And just as a side node, I am using this driver with the Xsens MTw Awinda system.

**Comment by qleonardolp** [comment]
> > Understood. Let's keep in touch about the vendor libraries. I'm also looking for way to be on the safe side in this package. As far as I know, the related SDK is now [officially distributed here](https://base.movella.com/s/article/Installing-the-correct-Software-Suite-for-different-generation-products?language=en_US).
> 
> I compared the libraries included in the MT Software Suite for Linux to the ones in your repository last week. It appears they have made some updates to both the libraries and their copyright notice, which now seems to allow modifications. However, after reading the EULA that comes with the MT Software Suite, it states that modifications are not permitted. This was also a reason why I contacted them for clarification about this. My guess is that the copyright of the older Xsens libraries in your repository has likely expired.
> 
> I will update you once I receive more information from Xsens. And just as a side node, I am using this driver with the Xsens MTw Awinda system.

Good! Maybe, if necessary, we can consider to use the [Open Source Xsens Device API](https://base.movella.com/s/article/Open-source-XDA-Xsens-Device-API?language=en_US). I remember to look up for this back in 2019, trying to cross compile it to run on a Rasp PI without success. However, since 2022 they open sourced the XDA, if I understood correctly.

**Comment by ksomml** [comment]
> Good! Maybe, if necessary, we can consider to use the [Open Source Xsens Device API](https://base.movella.com/s/article/Open-source-XDA-Xsens-Device-API?language=en_US). I remember to look up for this back in 2019, trying to cross compile it to run on a Rasp PI without success. However, since 2022 they open sourced the XDA, if I understood correctly.

Isn't the XDA (but just an older version) not already being used in this project? You are including the "xsensdeviceapi.h" in the "mt_w_main.cpp" file. Or do you mean to update the older XDA to the latest one from 2022, or something completely different? I have to say, that this is generally a new area in coding for me. That is also why I initially decided to just fix all errors and the C++ standard warnings for Xsens libraries in the current ROS2 implementation when building the package. Maybe you could let me know more about it as I figure that you most likely have more insight into drivers in general. My main problem just was that I am not sure if modifications to these library files are allowed, because the copyright notice at the very top in all of them states its not.

However the latest XDA from 2022 seems to be open source and according to the E-Mail from Xsens I have received yesterday:
> The new EULA in MT 2022 should apply, you could just follow the latest one.

..it seems that these older library files should also be free to modify and publish nowadays.

With this I believe I would just try to work on these warnings when building the ROS2 package. Or do you have another suggestion which might be the better way?

**Comment by ksomml** [comment]
So I've done some digging if you're still interested in this topic @qleonardolp

As far as I've found out, the public XDA 2022 (open-source) you mentioned before is only for MTi devices, meaning it won't support MTw Awinda Systems but could be compiled on a Raspberry Pi. The XDA with the MT Manager supports all Xsens devices, but is not directly open-source due to the .so files in the lib folder and this was most likely the cause why you couldn't build it on your Raspberry, as well as the person who opened a issue about this on the repository.

I've tried out the examples provided with the MT Software Suite (Linux) in `/usr/local/xsens`. The `example_mtw` in `xsens/examples/mtsdk/xda_cpp` would be the one that uses the non-open source XDA with `.so` files as far as I can tell. This one works with my Xsens MTw Awinda System. The example `example_mti_receive_data` in `xsens/examples/mtsdk/xda_public_cpp is the one, that uses the public XDA and does not work with my Xsens MTw Awinda System. Already the first lines of code this command is used which is exactly the same as in the first example:

`XsPortInfoArray portInfoArray = XsScanner::scanPorts();`

Normally this should not be different from the first example, but it gets stuck in a loop and cannot properly recognize the MTw Device in the USB Slot which makes me believe, that the `.so` files have a broader implementation for all Xsens devices and would also confirm what is written in the Xsens documentation about the public XDA (`doc/xsensdeviceapi/doc/html/p_publicxda.html`):

> This public XDA library contains following functionality:
> Device discovery - various scanners to scan for MTi devices on different interfaces, such as RS232 and USB.

My current plan would be to create a new repository (as your repository focuses on ROS1) and import the updated XDA library headers and `.so` files, as well as import my already implemented class structure.

Just wanted to let you know, maybe you have some feedback for me in that regard if you noticed something where I could be wrong.

I will report back here, if you are still interested in it.

**Comment by qleonardolp** [comment]
> So I've done some digging if you're still interested in this topic @qleonardolp
> 
> As far as I've found out, the public XDA 2022 (open-source) you mentioned before is only for MTi devices, meaning it won't support MTw Awinda Systems but could be compiled on a Raspberry Pi. The XDA with the MT Manager supports all Xsens devices, but is not directly open-source due to the .so files in the lib folder and this was most likely the cause why you couldn't build it on your Raspberry, as well as the person who opened a issue about this on the repository.
> 
> I've tried out the examples provided with the MT Software Suite (Linux) in `/usr/local/xsens`. The `example_mtw` in `xsens/examples/mtsdk/xda_cpp` would be the one that uses the non-open source XDA with `.so` files as far as I can tell. This one works with my Xsens MTw Awinda System. The example `example_mti_receive_data` in `xsens/examples/mtsdk/xda_public_cpp is the one, that uses the public XDA and does not work with my Xsens MTw Awinda System. Already the first lines of code this command is used which is exactly the same as in the first example:
> 
> `XsPortInfoArray portInfoArray = XsScanner::scanPorts();`
> 
> Normally this should not be different from the first example, but it gets stuck in a loop and cannot properly recognize the MTw Device in the USB Slot which makes me believe, that the `.so` files have a broader implementation for all Xsens devices and would also confirm what is written in the Xsens documentation about the public XDA (`doc/xsensdeviceapi/doc/html/p_publicxda.html`):
> 
> > This public XDA library contains following functionality:
> > Device discovery - various scanners to scan for MTi devices on different interfaces, such as RS232 and USB.
> 
> My current plan would be to create a new repository (as your repository focuses on ROS1) and import the updated XDA library headers and `.so` files, as well as import my already implemented class structure.
> 
> Just wanted to let you know, maybe you have some feedback for me in that regard if you noticed something where I could be wrong.
> 
> I will report back here, if you are still interested in it.

@ksomml, thanks for your time digging on it. Great job! As you might see I've been struggling to follow the things here (I do not recommend have a full time job and a PhD at the same time :| ) Your plan looks good to me. While I can't follow along and cooperate I'd like to support as far as I can. Right now I can guarantee that at least a link point out to your repo will be on my README here to forward newcomers looking for the ros2 version of this driver. :)

**Pull request closed without merging**
